[2017/03/07 11:42:45] :: [pool-1-thread-5] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/03/07 11:42:45] :: [pool-1-thread-5] :: Current Thread Name for the test is "pool-1-thread-5"<br><br>[2017/03/07 11:43:16] :: [pool-1-thread-5] :: The user has launched 'http://test.salesforce.com<br><br>[2017/03/07 11:43:17] :: [pool-1-thread-5] :: The user has creating SalesCreditINVorder<br><br>[2017/03/07 11:43:37] :: [pool-1-thread-5] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/03/07 11:44:11] :: [pool-1-thread-5] :: Exception occurred. null<br><br>[2017/03/07 11:44:21] :: [pool-1-thread-5] :: Closing the Browser Instance<br><br>