[2018/01/02 17:56:23] :: [pool-1-thread-2] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/02 17:56:23] :: [pool-1-thread-2] :: Current Thread Name for the test is "pool-1-thread-2"<br><br>[2018/01/02 17:57:10] :: [pool-1-thread-2] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/02 17:57:26] :: [pool-1-thread-2] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/02 17:57:28] :: [pool-1-thread-2] :: Successfully navigated to Home page<br><br>[2018/01/02 17:57:31] :: [pool-1-thread-2] :: Exception occurred. null<br><br>[2018/01/02 17:57:33] :: [pool-1-thread-2] :: Exception occurred. null value in entry: url=null<br><br>[2018/01/02 17:57:37] :: [pool-1-thread-2] :: Closing the Browser Instance<br><br>[2018/01/02 17:57:37] :: [pool-1-thread-2] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Commissions.java Method name: PrintingFiledExcelReport(3828)<br> File Name: Commissions.java Method name: erifyingParentAssetZuoraDetails(250)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/CLAWBACK_COMMISSIONS/ClawBack_Commissions_CrossOverDateAmendCancel2.feature Method name: Then I am verifying parent asset zuora details using "1" and "CrossOverDateAmendOrCancelNonInventory" and "Product"(8)<br><br>Complete Error Message: null<br><br><br>