[2018/01/04 13:08:14] :: [pool-1-thread-18] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/04 13:08:14] :: [pool-1-thread-18] :: Current Thread Name for the test is "pool-1-thread-18"<br><br>[2018/01/04 13:08:41] :: [pool-1-thread-18] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/04 13:08:42] :: [pool-1-thread-18] :: The user has creating RetentionCancel_NonInvorder<br><br>[2018/01/04 13:09:31] :: [pool-1-thread-18] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/04 13:10:02] :: [pool-1-thread-18] :: Unable to navigate to Home page<br><br>[2018/01/04 13:10:05] :: [pool-1-thread-18] :: Closing the Browser Instance<br><br>[2018/01/04 13:10:05] :: [pool-1-thread-18] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: verifyHP(198)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMD_CANCEL/Order_Cancel_NonInventory_Fivestreet_EUT_DL.feature Method name: Then I should be in "Home" page(8)<br><br>Complete Error Message: null<br><br><br>