[2017/04/28 11:39:48] :: [pool-1-thread-2] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/04/28 11:39:48] :: [pool-1-thread-2] :: Current Thread Name for the test is "pool-1-thread-2"<br><br>[2017/04/28 11:40:26] :: [pool-1-thread-2] :: The user has launched 'http://test.salesforce.com<br><br>[2017/04/28 11:40:53] :: [pool-1-thread-2] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/04/28 11:41:04] :: [pool-1-thread-2] :: The user has creating SalesCancelNONorder<br><br>[2017/04/28 11:41:07] :: [pool-1-thread-2] :: Successfully navigated to Home page<br><br>[2017/04/28 11:41:10] :: [pool-1-thread-2] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/04/28 11:46:00] :: [pool-1-thread-2] :: Exception occurred. null<br><br>[2017/04/28 11:46:10] :: [pool-1-thread-2] :: Closing the Browser Instance<br><br>[2017/04/28 11:46:11] :: [pool-1-thread-2] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Common.java Method name: loginUserNameAccountID(790)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMENDMENT/Cancel_Advantage_with_Credit_DL.feature Method name: When I login with "Emily Morrison" and launch "1"(9)<br><br>Complete Error Message: <br><br><br>