[2017/12/21 11:28:58] :: [pool-1-thread-3] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/12/21 11:28:58] :: [pool-1-thread-3] :: Current Thread Name for the test is "pool-1-thread-3"<br><br>[2017/12/21 11:29:17] :: [pool-1-thread-3] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2017/12/21 11:29:18] :: [pool-1-thread-3] :: The user has creating SalesCancelNONorder<br><br>[2017/12/21 11:29:26] :: [pool-1-thread-3] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/12/21 11:29:26] :: [pool-1-thread-3] :: Successfully navigated to Home page<br><br>[2017/12/21 11:29:26] :: [pool-1-thread-3] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/12/21 11:29:27] :: [pool-1-thread-3] :: Exception occurred. Unexpected end of ZLIB input stream<br><br>[2017/12/21 11:29:30] :: [pool-1-thread-3] :: Closing the Browser Instance<br><br>[2017/12/21 11:29:30] :: [pool-1-thread-3] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Common.java Method name: loginUserNameAccountID(783)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMD1/New_Sales_Cancel_DomainName_NonInventory_With_Credit_Amount.feature Method name: When I login with "Emily Morrison" and launch "1"(8)<br><br>Complete Error Message: null<br><br><br>