[2018/02/15 17:44:29] :: [pool-1-thread-5] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/02/15 17:44:30] :: [pool-1-thread-5] :: Current Thread Name for the test is "pool-1-thread-5"<br><br>[2018/02/15 17:45:14] :: [pool-1-thread-5] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/02/15 17:45:15] :: [pool-1-thread-5] :: The user has creating SalesCancel_Invorder<br><br>[2018/02/15 17:50:15] :: [pool-1-thread-5] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/02/15 17:50:46] :: [pool-1-thread-5] :: Unable to navigate to Home page<br><br>[2018/02/15 17:50:50] :: [pool-1-thread-5] :: Closing the Browser Instance<br><br>[2018/02/15 17:50:51] :: [pool-1-thread-5] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: verifyHP(198)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Cancel/New_Sales_Cancel_Inventory_CFCB_EUT_WithOutCreditAmount_DL3.feature Method name: Then I should be in "Home" page(8)<br><br>Complete Error Message: null<br><br><br>