[2017/03/07 11:55:15] :: [pool-1-thread-3] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/03/07 11:55:15] :: [pool-1-thread-3] :: Current Thread Name for the test is "pool-1-thread-3"<br><br>[2017/03/07 11:55:53] :: [pool-1-thread-3] :: The user has launched 'http://test.salesforce.com<br><br>[2017/03/07 11:55:53] :: [pool-1-thread-3] :: The user has creating RetBuyoutINVorder<br><br>[2017/03/07 11:56:40] :: [pool-1-thread-3] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/03/07 11:56:41] :: [pool-1-thread-3] :: Successfully navigated to Home page<br><br>[2017/03/07 11:56:41] :: [pool-1-thread-3] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2017/03/07 11:56:54] :: [pool-1-thread-3] :: Successfully Assets Type is visible= Connection(SM) for Co-Brokerage-80447 .<br><br>[2017/03/07 11:57:07] :: [pool-1-thread-3] :: Successfully Account ID is visible= 001j000000bfV2a .<br><br>[2017/03/07 11:57:35] :: [pool-1-thread-3] :: Successfully Account Name is visible 001j000000bfV2a .<br><br>[2017/03/07 11:57:51] :: [pool-1-thread-3] :: Successfully Enter contact email<br><br>[2017/03/07 11:57:51] :: [pool-1-thread-3] :: Exception occurred. C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\SalesForce\OutPutData.xlsx (The process cannot access the file because it is being used by another process)<br><br>[2017/03/07 11:57:54] :: [pool-1-thread-3] :: Closing the Browser Instance<br><br>[2017/03/07 11:57:54] :: [pool-1-thread-3] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Common.java Method name: changeContactEmail(851)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMDMAIL/AMDMAIL/Copy (2) of Copy of ContactEmailChangeForAllTC.feature Method name: And change contact Email(10)<br><br>Complete Error Message: <br><br><br>