[2018/02/12 18:14:00] :: [pool-1-thread-4] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/02/12 18:14:00] :: [pool-1-thread-4] :: Current Thread Name for the test is "pool-1-thread-4"<br><br>[2018/02/12 18:14:25] :: [pool-1-thread-4] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/02/12 18:14:42] :: [pool-1-thread-4] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/02/12 18:15:13] :: [pool-1-thread-4] :: Unable to navigate to Home page<br><br>[2018/02/12 18:15:17] :: [pool-1-thread-4] :: Closing the Browser Instance<br><br>[2018/02/12 18:15:17] :: [pool-1-thread-4] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: SalesForce.java Method name: verifyHP(198)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/CLAWBACK_COMMISSIONS/ClawBack_Commissions_CrossOverDateAmendCancel4.feature Method name: Then I should be in "Home" page(7)<br><br>Complete Error Message: null<br><br><br>