[2018/01/08 16:06:34] :: [pool-1-thread-12] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/08 16:06:35] :: [pool-1-thread-12] :: Current Thread Name for the test is "pool-1-thread-12"<br><br>[2018/01/08 16:06:47] :: [pool-1-thread-12] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/08 16:06:48] :: [pool-1-thread-12] :: The user has creating NonInv_Paidorder<br><br>[2018/01/08 16:07:02] :: [pool-1-thread-12] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/08 16:07:03] :: [pool-1-thread-12] :: Successfully navigated to Home page<br><br>[2018/01/08 16:07:04] :: [pool-1-thread-12] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/01/08 16:07:17] :: [pool-1-thread-12] :: Exception occurred. 3<br><br>[2018/01/08 16:07:22] :: [pool-1-thread-12] :: Closing the Browser Instance<br><br>[2018/01/08 16:07:22] :: [pool-1-thread-12] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: sfdc.java Method name: loginUserNameAccountID(395)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/NON/Modify_NonInventory_Paid_TPCRM_DL4.feature Method name: When I am entering "Emily Morrison" and launch "1"(9)<br><br>Complete Error Message: null<br><br><br>