[2017/03/20 12:59:27] :: [pool-1-thread-29] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/03/20 12:59:28] :: [pool-1-thread-29] :: Current Thread Name for the test is "pool-1-thread-29"<br><br>[2017/03/20 12:59:58] :: [pool-1-thread-29] :: The user has launched 'http://test.salesforce.com<br><br>[2017/03/20 12:59:58] :: [pool-1-thread-29] :: The user has creating TermOverideINVorder<br><br>[2017/03/20 13:00:20] :: [pool-1-thread-29] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/03/20 13:00:53] :: [pool-1-thread-29] :: Exception occurred. null<br><br>[2017/03/20 13:01:00] :: [pool-1-thread-29] :: Closing the Browser Instance<br><br>[2017/03/20 13:01:00] :: [pool-1-thread-29] ::  File Name: Assert.java Method name: fail(91)<br> File Name: Assert.java Method name: assertTrue(43)<br> File Name: Assert.java Method name: assertTrue(54)<br> File Name: Common.java Method name: changeStatusSales(161)<br> File Name: SalesForce.java Method name: loginSF(100)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMENDMENT/New_Sales_Cancel_Fivestreet_NonInventory_With_Credit_Amount_DL.feature Method name: When I login to SalesForce(7)<br><br>Complete Error Message: <br><br><br>