[2017/04/25 18:26:56] :: [pool-1-thread-4] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2017/04/25 18:26:57] :: [pool-1-thread-4] :: Current Thread Name for the test is "pool-1-thread-4"<br><br>[2017/04/25 18:27:53] :: [pool-1-thread-4] :: The user has launched 'http://test.salesforce.com<br><br>[2017/04/25 18:28:18] :: [pool-1-thread-4] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2017/04/25 18:28:24] :: [pool-1-thread-4] :: Successfully navigated to Home page<br><br>[2017/04/25 18:29:28] :: [pool-1-thread-4] :: Exception occurred. null<br><br>[2017/04/25 18:29:31] :: [pool-1-thread-4] :: Exception occurred. null value in entry: url=null<br><br>