[2018/02/15 17:05:02] :: [pool-1-thread-13] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/02/15 17:05:02] :: [pool-1-thread-13] :: Current Thread Name for the test is "pool-1-thread-13"<br><br>[2018/02/15 17:05:26] :: [pool-1-thread-13] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/02/15 17:05:27] :: [pool-1-thread-13] :: The user has creating SalesCancel_Invorder<br><br>[2018/02/15 17:06:07] :: [pool-1-thread-13] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/02/15 17:06:09] :: [pool-1-thread-13] :: Successfully navigated to Home page<br><br>[2018/02/15 17:06:10] :: [pool-1-thread-13] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/02/15 17:06:31] :: [pool-1-thread-13] :: Exception occurred. 3<br><br>[2018/02/15 17:06:37] :: [pool-1-thread-13] :: Closing the Browser Instance<br><br>[2018/02/15 17:06:37] :: [pool-1-thread-13] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: sfdc.java Method name: loginUserNameAccountID(395)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Cancel/New_Sales_Cancel_Inventory_Connections(SM)for_Seller_Bundle _DL.feature Method name: When I am entering "Emily Morrison" and launch "1"(9)<br><br>Complete Error Message: null<br><br><br>