[2018/01/02 12:51:07] :: [pool-1-thread-8] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/02 12:51:07] :: [pool-1-thread-8] :: Current Thread Name for the test is "pool-1-thread-8"<br><br>[2018/01/02 12:51:21] :: [pool-1-thread-8] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/02 12:51:22] :: [pool-1-thread-8] :: The user has creating RetentionCancel_NonInvorder<br><br>[2018/01/02 12:51:36] :: [pool-1-thread-8] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/02 12:51:37] :: [pool-1-thread-8] :: Successfully navigated to Home page<br><br>[2018/01/02 12:51:38] :: [pool-1-thread-8] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/01/02 12:51:46] :: [pool-1-thread-8] :: Exception occurred. null<br><br>[2018/01/02 12:51:50] :: [pool-1-thread-8] :: Closing the Browser Instance<br><br>[2018/01/02 12:51:50] :: [pool-1-thread-8] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: sfdc.java Method name: loginUserNameAccountID(395)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/AMD_CANCEL/Order_Cancel_NonInventory_Fivestreet_EUT_DL.feature Method name: When I am entering "Emily Morrison" and launch "1"(9)<br><br>Complete Error Message: null<br><br><br>