[2018/02/13 17:10:15] :: [pool-1-thread-1] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/02/13 17:10:15] :: [pool-1-thread-1] :: Current Thread Name for the test is "pool-1-thread-1"<br><br>[2018/02/13 17:10:35] :: [pool-1-thread-1] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/02/13 17:10:35] :: [pool-1-thread-1] :: The user has creating RenewNonInvorder<br><br>[2018/02/13 17:10:54] :: [pool-1-thread-1] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/02/13 17:10:54] :: [pool-1-thread-1] :: Successfully navigated to Home page<br><br>[2018/02/13 17:19:29] :: [pool-1-thread-1] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/02/13 17:19:32] :: [pool-1-thread-1] :: Exception occurred. null<br><br>[2018/02/13 17:19:34] :: [pool-1-thread-1] :: Closing the Browser Instance<br><br>[2018/02/13 17:19:34] :: [pool-1-thread-1] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: Common.java Method name: loginUserNameAccountID(783)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/Advantage_Renewals/Advantage_Renewals_Pro_brand.feature Method name: When I login with "Emily Morrison" and launch "81"(9)<br><br>Complete Error Message: null<br><br><br>