[2018/01/02 17:55:28] :: [pool-1-thread-5] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/02 17:55:28] :: [pool-1-thread-5] :: Current Thread Name for the test is "pool-1-thread-5"<br><br>[2018/01/02 17:55:38] :: [pool-1-thread-5] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/02 17:55:52] :: [pool-1-thread-5] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/02 17:55:53] :: [pool-1-thread-5] :: Successfully navigated to Home page<br><br>[2018/01/02 17:55:58] :: [pool-1-thread-5] :: Exception occurred. null<br><br>