[2018/01/17 15:11:02] :: [pool-1-thread-8] :: Base path for the test = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\<br><br>[2018/01/17 15:11:02] :: [pool-1-thread-8] :: Current Thread Name for the test is "pool-1-thread-8"<br><br>[2018/01/17 15:11:11] :: [pool-1-thread-8] :: The user has launched 'https://qainc--qa.cs30.my.salesforce.com<br><br>[2018/01/17 15:11:12] :: [pool-1-thread-8] :: The user has creating BroNINeworder<br><br>[2018/01/17 15:11:27] :: [pool-1-thread-8] :: arindom.das@move.com.qa has successfully loggedin<br><br>[2018/01/17 15:11:28] :: [pool-1-thread-8] :: Successfully navigated to Home page<br><br>[2018/01/17 15:11:29] :: [pool-1-thread-8] :: File path is = C:\New Selenium\Salesforce_QA_Automation\ADT_Resources\ .<br><br>[2018/01/17 15:11:44] :: [pool-1-thread-8] :: Exception occurred. null<br><br>[2018/01/17 15:11:51] :: [pool-1-thread-8] :: Closing the Browser Instance<br><br>[2018/01/17 15:11:51] :: [pool-1-thread-8] ::  File Name: Assert.java Method name: fail(86)<br> File Name: Assert.java Method name: assertTrue(41)<br> File Name: Assert.java Method name: assertTrue(52)<br> File Name: sfdc.java Method name: loginUserNameAccountID(395)<br> File Name: C:/New Selenium/Salesforce_QA_Automation/ADT_Resources/SalesForce/FeatureFiles/BROKER_NEWORDER/Commission_MarketSnapshot_NonInventory_XL_Broker.feature Method name: When I am entering "Steven Jackson" and launch "4"(9)<br><br>Complete Error Message: null<br><br><br>